name: 自动部署到服务器（FTP）
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 部署子主题到服务器
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "114.215.181.118"
          username: "musicalbum"
          password: ${{ secrets.FTP_PASSWORD }}
          port: "2121"
          protocol: ftp
          local-dir: "src/wp-content/themes/musicalbum-child/"
          server-dir: "wp-content/themes/musicalbum-child/"
          timeout: 60000
          log-level: verbose

      - name: 部署插件到服务器
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "114.215.181.118"
          username: "musicalbum"
          password: ${{ secrets.FTP_PASSWORD }}
          port: "2121"
          protocol: ftp
          local-dir: "src/wp-content/plugins/musicalbum-integrations/"
          server-dir: "wp-content/plugins/musicalbum-integrations/"
          timeout: 60000
          log-level: verbose

      - name: 部署背景音乐插件到服务器
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "114.215.181.118"
          username: "musicalbum"
          password: ${{ secrets.FTP_PASSWORD }}
          port: "2121"
          protocol: ftp
          local-dir: "src/wp-content/plugins/background-music/"
          server-dir: "wp-content/plugins/background-music/"
          timeout: 60000
          log-level: verbose
        
      - name: 部署智能推荐插件到服务器
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: "114.215.181.118"
          username: "musicalbum"
          password: ${{ secrets.FTP_PASSWORD }}
          port: "2121"
          protocol: ftp
          local-dir: "src/wp-content/plugins/musicalbum-recommendation/"
          server-dir: "wp-content/plugins/musicalbum-recommendation/"
          timeout: 60000
          log-level: verbose